name: "Terraform Pull Request Commenter"
description: "Adds opinionated comments to a PR from Terraform fmt/init/plan output. The output should be written to a file first."
author: "Try GRIT"
branding:
  icon: "git-pull-request"
  color: "purple"
inputs:
  commenter_type:
    description: "The type of comment. Options: [fmt, init, plan]."
    required: true
  commenter_input:
    description: "Path to the file containing the output to comment on."
    required: true
  commenter_type_exitcode:
    description: "The exit code from a previous step output."
    required: true
    default: "0"
runs:
  using: "composite"
  steps:
    - name: Run commentor script
      shell: bash
      run: |
        # Create a temporary file for the input
        echo "${{ inputs.commenter_input }}" > /tmp/terraform_output.txt

        # Set default exit code if empty
        EXIT_CODE="${{ inputs.commenter_type_exitcode }}"
        if [ -z "$EXIT_CODE" ]; then
          EXIT_CODE="0"
        fi

        chmod +x ${{ github.action_path }}/commmentor.sh
        ${{ github.action_path }}/commmentor.sh "${{ inputs.commenter_type }}" "/tmp/terraform_output.txt" "$EXIT_CODE"
