name: "Terraform Pull Request Commenter"
description: "Adds opinionated comments to a PR from Terraform fmt/init/plan output."
author: "Try GRIT"
branding:
  icon: "git-pull-request"
  color: "purple"
inputs:
  command:
    description: "The terraform command to run (fmt, plan, etc.)"
    required: true
  directory:
    description: "The directory containing terraform files"
    required: false
    default: "."
  workspace:
    description: "Terraform workspace name"
    required: false
    default: "default"
  github_token:
    description: "GitHub token for posting comments"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.command }}
    - ${{ inputs.directory }}
  env:
    GITHUB_TOKEN: ${{ inputs.github_token }}
    TERRAFORM_WORKSPACE: ${{ inputs.workspace }}
