name: "Terraform Pull Request Commenter"
description: "Adds opinionated comments to a PR from Terraform fmt/init/plan output."
author: "Try GRIT"
branding:
  icon: "git-pull-request"
  color: "purple"
inputs:
  command:
    description: "The terraform command to run (fmt, init, plan)"
    required: true
  directory:
    description: "Directory containing terraform files"
    required: true
  workspace:
    description: "Terraform workspace to use"
    required: false
    default: "default"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.command }}
    - ${{ inputs.directory }}
  env:
    GITHUB_TOKEN: $GITHUB_TOKEN
    TERRAFORM_WORKSPACE: ${{ inputs.workspace }}
