name: "Terraform Pull Request Commenter"
description: "Adds opinionated comments to a PR from Terraform fmt/init/plan output."
author: "Try GRIT"
branding:
  icon: "git-pull-request"
  color: "purple"
inputs:
  type:
    description: "The type of comment (fmt, plan, etc.)"
    required: true
  output:
    description: "The terraform command output"
    required: true
  exit_code:
    description: "The exit code from the terraform command"
    required: true
    default: "0"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.type }}
    - ${{ inputs.output }}
    - ${{ inputs.exit_code }}
  env:
    GITHUB_TOKEN: ${{ github.token }}
    TERRAFORM_WORKSPACE: ${{ github.workspace }}
