name: "Terraform Pull Request Commenter"
description: "Adds opinionated comments to a PR from Terraform fmt/init/plan output."
author: "Try GRIT"
branding:
  icon: "git-pull-request"
  color: "purple"
inputs:
  type:
    description: "The type of comment (fmt, plan, etc.)"
    required: true
  output:
    description: "The terraform command output"
    required: true
  exit_code:
    description: "The exit code from the terraform command"
    required: true
    default: "0"
  github_token:
    description: "GitHub token for posting comments"
    required: true
  workspace:
    description: "Terraform workspace name"
    required: false
    default: "default"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.type }}
    - ${{ inputs.output }}
    - ${{ inputs.exit_code }}
  env:
    GITHUB_TOKEN: ${{ inputs.github_token }}
    TERRAFORM_WORKSPACE: ${{ inputs.workspace }}
